#!/usr/bin/env bash
# This script installs and integrates Grafana, Loki and Promtail

'Step1: Installing Grafana on Ubuntu'

# Import the GPG key used by the Grafana package
wget -q -O - https://packages.grafana.com/gpg.key | sudo apt-key add -

# Add the Grafana repository to the APT sources
sudo add-apt-repository "deb https://packages.grafana.com/oss/deb stable main"

# Update the package lists
sudo apt update

# Install the grafana
sudo apt-get install grafana

# Start and enable the Grafana service
sudo systemctl start grafana-server
sudo systemctl enable grafana-server

# Allow inbound traffic on port 3000
sudo ufw allow 3000/tcp || echo "UFW command failed, continuing with the script..."

'Step2: Installing Grafana Loki on Ubuntu'

# Download the Loki binary
wget https://github.com/grafana/loki/releases/download/v3.4.2/loki-linux-amd64.zip

# Install unzip if you don’t have it already
sudo apt-get install unzip

# Unzip the downloaded file and remove the zip file
unzip loki-linux-amd64.zip
rm loki-linux-amd64.zip

# Make the Loki binary executable
chmod +x loki-linux-amd64

# Move it to a directory to the PATH and confirm Loki installation
sudo mv loki-linux-amd64 /usr/local/bin/loki
loki --version

# Create data directories required for Loki
sudo mkdir -p /data/loki

# Removing existing loki-local-config.yaml and service file in case present
sudo rm /etc/loki-local-config.yaml
sudo rm /etc/systemd/system/loki.service

# Gets the config files for Loki and place it in /etc/loki-local-config.yaml
sudo wget -O /etc/loki-local-config.yaml https://raw.githubusercontent.com/grafana/loki/v3.4.2/cmd/loki/loki-local-config.yaml 

# Loop to get and confirm the IP address
while true; do
    read -rp "Enter your server IP address: " server_ip
    read -rp "Confirm your server IP address: " confirm_ip

    # Check if both IPs match
    if [[ "$server_ip" == "$confirm_ip" ]]; then
        echo "Server IP confirmed: $server_ip"
        break
    else
        echo "IP addresses do not match. Please try again."
    fi
done

# You can now use the confirmed IP address
echo "Proceeding with configuration for server IP: $server_ip"

# Include Server IP on Loki config file
sudo sed -i "s|localhost|$server_ip|g" /etc/loki-local-config.yaml

# Create a systemd service file for Loki to manage its execution
cp loki-serv loki.service
sudo mv loki.service /etc/systemd/system/

# Save the file and reload the systemd daemon to apply changes
sudo systemctl daemon-reload

# Start the Loki service and enable it and check status
sudo systemctl start loki.service
sudo systemctl enable loki.service
sudo systemctl status loki.service

'Step3: Install Promtail Agent on Ubuntu'

# Download Promtail binary file
wget https://github.com/grafana/loki/releases/download/v3.4.2/promtail-linux-amd64.zip

# Unzip the downloaded file and remove the zip file
unzip promtail-linux-amd64.zip
rm promtail-linux-amd64.zip

# Move it to a directory to the PATH and confirm Promtail installation
sudo mv promtail-linux-amd64 /usr/local/bin/promtail
promtail --version

# Removing existing promtail-local-config.yaml and service file in case present
sudo rm /etc/promtail-local-config.yaml
sudo rm /etc/systemd/system/promtail.service

# Gets the config files for Promtail and place it in /etc/promtail-local-config.yaml
sudo wget -O /etc/promtail-local-config.yaml https://raw.githubusercontent.com/grafana/loki/v3.4.2/clients/cmd/promtail/promtail-docker-config.yaml

# Include Server IP on Loki config file
sudo sed -i "s|http://localhost:3100/loki/api/v1/push|http://$server_ip:3100/loki/api/v1/push|g" /etc/promtail-local-config.yaml

# Create a systemd service file for Loki to manage its execution
cp prom-serv promtail.service
sudo mv promtail.service /etc/systemd/system/

# Reload the systemd daemon to apply changes
sudo systemctl daemon-reload

# Start the Promtail service and check status
sudo systemctl start promtail.service
sudo systemctl status promtail.service

# Till now we have installed the Grafana. Loki and Promtail on our system. So the next step is to configure the loki and start visualizing the data in Grafana.
