#!/usr/bin/env bash

# Download the Loki binary
wget https://github.com/grafana/loki/releases/download/v3.4.2/loki-linux-amd64.zip

# Install unzip if you don’t have it already
sudo apt-get install unzip

# Unzip the downloaded file
unzip loki-linux-amd64.zip

# Make the Loki binary executable
chmod +x loki-linux-amd64

# Move it to a directory in your PATH (optional but useful)
# sudo mv loki-linux-amd64 /usr/local/bin/loki

# Gets the config files for Loki and Promtail
wget https://raw.githubusercontent.com/grafana/loki/v3.4.2/cmd/loki/loki-local-config.yaml
wget https://raw.githubusercontent.com/grafana/loki/v3.4.2/clients/cmd/promtail/promtail-docker-config.yaml -O promtail-local-config.yaml

# Starting Loki
./loki-linux-amd64 -config.file=loki-local-config.yaml
