{
 "title": "Packages",
 "tags": [
  "linux",
  "package-updates"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "2h",
 "panels": [
  {
   "title": "Automatic updates",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"automatic_updates.log\"} |= ``"
    }
   ]
  },
  {
   "title": "apt.log",
   "type": "logs",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"apt_logs\"} |= ``"
    }
   ]
  },
  {
   "title": "dpkg.log",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"package_mgt_logs\"} |= ``"
    }
   ]
  }
 ]
}