apiVersion: 1

# Deletes unused data sources
#deleteDatasources:
#  - name: TestData
#    orgId: 1
#  - name: DS_LOKI
#    orgId: 1
#  - name: DS_PROMETHEUS
#    orgId: 1
 
prune: true
datasources:
  - name: Loki
    uid: "P8E80F9AEF21F6940"
    type: loki
    access: proxy 
    url: http://localhost:3100

  - name: Mimir
    uid: "PAE45454D0EDB9216"
    type: prometheus
    access: proxy
    url: http://localhost:9009/prometheus
